import { createServer } from "node:http";
import { execFile } from "node:child_process";
import { access, readFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
const exec = promisify(execFile), host="127.0.0.1", port=Number(process.env.PORT||43110), publicDir=join(process.cwd(),"public");
const candidates=[process.env.OPENCLAW_CLI,join(homedir(),".npm-global/bin/openclaw"),join(homedir(),".local/bin/openclaw"),join(homedir(),"AppData/Roaming/npm/openclaw.cmd"),"/opt/homebrew/bin/openclaw","/usr/local/bin/openclaw","/usr/bin/openclaw"].filter(Boolean);
let cliPath; const clients=new Map(); let hadClient=false,emptySince=null;
async function findCli(){if(cliPath)return cliPath;for(const p of candidates)try{await access(p);return cliPath=p}catch{}throw Error("找不到 OpenClaw CLI。请设置 OPENCLAW_CLI 后重新启动。")}
async function run(args,timeout=20000){try{const{stdout}=await exec(await findCli(),args,{timeout,maxBuffer:10485760,env:{...process.env,NO_COLOR:"1"}});return stdout.trim()}catch(e){const d=[e.stderr,e.stdout,e.message].filter(Boolean).join("\n");if(d.includes("pairing required"))throw Error("OpenClaw Gateway 要求设备配对。请先在控制面板的 Devices / 设备页面批准 CLI 设备。");throw Error(d.split("\n").find(x=>/error|failed|denied|invalid|not found/i.test(x))||d.split("\n")[0])}}
function parse(s){return JSON.parse(s.slice(s.indexOf("{"),s.lastIndexOf("}")+1))} function send(res,status,body){res.writeHead(status,{"content-type":"application/json; charset=utf-8","cache-control":"no-store"});res.end(JSON.stringify(body))}
async function body(req){let s="";for await(const c of req)s+=c;return s?JSON.parse(s):{}}
async function call(method,params={}){return parse(await run(["gateway","call",method,"--json","--timeout","20000","--params",JSON.stringify(params)],25000))}
async function labels(result){const map=new Map(),sessions=result.sessions||[],ids=[...new Set(sessions.map(x=>x.agentId).filter(x=>/^[\w-]+$/.test(x)))];await Promise.all(ids.map(async id=>{try{const store=JSON.parse(await readFile(join(homedir(),".openclaw","agents",id,"sessions","sessions.json"),"utf8"));for(const[k,v]of Object.entries(store))map.set(k,v)}catch{}}));return{...result,sessions:sessions.map(x=>map.get(x.key)?.label?{...x,label:map.get(x.key).label}:x)}}
async function api(req,res,path){if(req.method==="POST"&&path==="/api/client/open"){const b=await body(req);if(b.id){clients.set(b.id,Date.now());hadClient=true;emptySince=null}return send(res,200,{ok:true})}if(req.method==="POST"&&path==="/api/client/close"){clients.delete((await body(req)).id);return send(res,200,{ok:true})}if(req.method==="GET"&&path==="/api/status")return send(res,200,{cli:await findCli(),version:await run(["--version"]),status:await run(["gateway","status"])});if(req.method==="GET"&&path==="/api/sessions")return send(res,200,await labels(parse(await run(["sessions","--all-agents","--limit","all","--json"]))));if(req.method!=="POST")return send(res,405,{error:"Method not allowed"});const b=await body(req);const actions={"/api/sessions/create":["sessions.create",{agentId:b.agentId||"main",...(b.label?.trim()?{label:b.label.trim()}:{})}],"/api/sessions/rename":["sessions.patch",{key:b.key,label:b.label?.trim()||null}],"/api/sessions/reset":["sessions.reset",{key:b.key}],"/api/sessions/abort":["sessions.abort",{key:b.key}],"/api/sessions/delete":["sessions.delete",{key:b.key,deleteTranscript:b.deleteTranscript===true}]};if(!actions[path])return send(res,404,{error:"Not found"});send(res,200,await call(...actions[path]))}
const server=createServer(async(req,res)=>{try{const u=new URL(req.url,`http://${host}:${port}`);if(u.pathname.startsWith("/api/"))return await api(req,res,u.pathname);const f=u.pathname==="/"?"index.html":u.pathname.slice(1);if(!/^[\w.-]+$/.test(f))return send(res,404,{error:"Not found"});const c=await readFile(join(publicDir,f)),type=f.endsWith(".css")?"text/css":f.endsWith(".js")?"text/javascript":f.endsWith(".svg")?"image/svg+xml":"text/html";res.writeHead(200,{"content-type":`${type}; charset=utf-8`});res.end(c)}catch(e){send(res,500,{error:e.message})}});server.listen(port,host,()=>console.log(`OpenClaw 会话管理器已启动：http://${host}:${port}`));setInterval(()=>{const now=Date.now();for(const[id,t]of clients)if(now-t>8000)clients.delete(id);if(!hadClient||clients.size){emptySince=null;return}emptySince??=now;if(now-emptySince>5000)server.close(()=>process.exit(0))},1000).unref();
